### ISSUE TITLE
Exporter is Crashing

### ISSUE THREAD

**Issue by tiagoReichert** [larscheid-schmitzhermes/prometheus-filesystem-exporter#4]
It generated the prometheus metric for "LOGIN" corretly, however, when the second metric "CODE_TO_TOKEN" was created the exporter crashed:

```log
8/8/2018 2:45:29 PM2018/08/08 17:45:29 Watching /container/metrics for metrics
8/8/2018 2:45:45 PM2018/08/08 17:45:45 Attempting to generate metric from file: /container/metrics/keycloak_events_total;realm=master;type=LOGIN
8/8/2018 2:45:45 PM2018/08/08 17:45:45 Attempting to update metric with value written to: /container/metrics/keycloak_events_total;realm=master;type=LOGIN
8/8/2018 2:45:45 PM2018/08/08 17:45:45 Setting metric for /container/metrics/keycloak_events_total;realm=master;type=LOGIN to 0.0000000000
8/8/2018 2:45:45 PM2018/08/08 17:45:45 Attempting to update metric with value written to: /container/metrics/keycloak_events_total;realm=master;type=LOGIN
8/8/2018 2:45:45 PM2018/08/08 17:45:45 Setting metric for /container/metrics/keycloak_events_total;realm=master;type=LOGIN to 0.0000000000
8/8/2018 2:45:45 PM2018/08/08 17:45:45 Attempting to update metric with value written to: /container/metrics/keycloak_events_total;realm=master;type=LOGIN
8/8/2018 2:45:45 PM2018/08/08 17:45:45 Setting metric for /container/metrics/keycloak_events_total;realm=master;type=LOGIN to 1.0000000000
8/8/2018 2:45:46 PM2018/08/08 17:45:46 Attempting to generate metric from file: /container/metrics/keycloak_events_total;realm=master;type=CODE_TO_TOKEN
8/8/2018 2:45:46 PMpanic: a previously registered descriptor with the same fully-qualified name as Desc{fqName: "keycloak_events_total", help: "Auto generated from filesystem path: /container/metrics/keycloak_events_total;realm=master;type=CODE_TO_TOKEN", constLabels: {realm="master",type="CODE_TO_TOKEN"}, variableLabels: []} has different label names or a different help string
8/8/2018 2:45:46 PM
8/8/2018 2:45:46 PMgoroutine 8 [running]:
8/8/2018 2:45:46 PMgithub.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc420010700, 0xc42021ff00, 0x1, 0x1)
8/8/2018 2:45:46 PM	/Users/tobiaslarscheid/go/src/github.com/prometheus/client_golang/prometheus/registry.go:353 +0x92
8/8/2018 2:45:46 PMgithub.com/prometheus/client_golang/prometheus.MustRegister(0xc42021ff00, 0x1, 0x1)
8/8/2018 2:45:46 PM	/Users/tobiaslarscheid/go/src/github.com/prometheus/client_golang/prometheus/registry.go:152 +0x53
8/8/2018 2:45:46 PMmain.getOrCreateMetricForPath(0xc42013c690, 0x48, 0xc42003af00, 0xc420010f01)
8/8/2018 2:45:46 PM	/Users/tobiaslarscheid/go/src/github.com/larscheid-schmitzhermes/prometheus-filesystem-exporter/main.go:79 +0x33d
8/8/2018 2:45:46 PMmain.main.func1(0xc420012c30)
8/8/2018 2:45:46 PM	/Users/tobiaslarscheid/go/src/github.com/larscheid-schmitzhermes/prometheus-filesystem-exporter/main.go:41 +0x14f
8/8/2018 2:45:46 PMcreated by main.main
8/8/2018 2:45:46 PM	/Users/tobiaslarscheid/go/src/github.com/larscheid-schmitzhermes/prometheus-filesystem-exporter/main.go:52 +0xee
```

This Issue seems to be something similar to the #1

**Comment by tiagoReichert** [comment]
**Problem found:**
The image with _latest_ tag on your Dockerhub is not the latest (v1.0.0) image.

It works using the image tag _1.0.0_, so please update the image on your Dockerhub with the _latest_ tag to be the latest version

**Comment by tobilarscheid** [comment]
shit, good catch! tag is fixed now. Thank you!
